package dev.shaaf.keycloak.mcp.server;

/**
 * All operations exposed by the unified {@link KeycloakTool}. Each value must have a
 * {@link dev.shaaf.keycloak.mcp.server.commands.KeycloakCommand} implementation registered
 * in {@link dev.shaaf.keycloak.mcp.server.commands.CommandRegistry} (CDI, unless disabled in config).
 */
public enum KeycloakOperation {

    // User
    GET_USERS,
    GET_USER_BY_USERNAME,
    CREATE_USER,
    DELETE_USER,
    UPDATE_USER,
    GET_USER_BY_ID,
    GET_USER_GROUPS,
    ADD_USER_TO_GROUP,
    REMOVE_USER_FROM_GROUP,
    GET_USER_ROLES,
    ADD_ROLE_TO_USER,
    REMOVE_ROLE_FROM_USER,
    RESET_PASSWORD,
    SEND_VERIFICATION_EMAIL,
    COUNT_USERS,

    // Realm
    GET_REALMS,
    GET_REALM,
    CREATE_REALM,
    DELETE_REALM,
    UPDATE_REALM,
    SET_REALM_ENABLED,
    GET_REALM_EVENTS_CONFIG,
    UPDATE_REALM_EVENTS_CONFIG,

    // Client
    GET_CLIENTS,
    GET_CLIENT,
    CREATE_CLIENT,
    UPDATE_CLIENT,
    DELETE_CLIENT,
    GENERATE_CLIENT_SECRET,
    GET_CLIENT_SECRET,
    GET_CLIENT_ROLES,
    GET_CLIENT_PROTOCOL_MAPPERS,
    ADD_PROTOCOL_MAPPER_TO_CLIENT,
    GET_SERVICE_ACCOUNT_USER,
    CREATE_CLIENT_ROLE,
    DELETE_CLIENT_ROLE,

    // Client scope
    GET_CLIENT_SCOPES,
    GET_CLIENT_SCOPE,
    CREATE_CLIENT_SCOPE,
    UPDATE_CLIENT_SCOPE,
    DELETE_CLIENT_SCOPE,
    GET_DEFAULT_CLIENT_SCOPES,
    GET_OPTIONAL_CLIENT_SCOPES,
    ADD_DEFAULT_CLIENT_SCOPE,
    ADD_OPTIONAL_CLIENT_SCOPE,
    REMOVE_DEFAULT_CLIENT_SCOPE,
    REMOVE_OPTIONAL_CLIENT_SCOPE,
    GET_CLIENT_SCOPE_PROTOCOL_MAPPERS,
    ADD_PROTOCOL_MAPPER_TO_CLIENT_SCOPE,
    UPDATE_CLIENT_SCOPE_PROTOCOL_MAPPER,
    DELETE_CLIENT_SCOPE_PROTOCOL_MAPPER,

    // Realm roles (composite, etc.)
    GET_REALM_ROLES,
    GET_REALM_ROLE,
    CREATE_REALM_ROLE,
    UPDATE_REALM_ROLE,
    DELETE_REALM_ROLE,
    GET_ROLE_COMPOSITES,
    ADD_COMPOSITE_TO_ROLE,
    REMOVE_COMPOSITE_FROM_ROLE,

    // Group
    GET_GROUPS,
    GET_GROUP,
    GET_GROUP_MEMBERS,
    GET_SUBGROUPS,
    GET_GROUP_ROLES,
    CREATE_GROUP,
    UPDATE_GROUP,
    DELETE_GROUP,
    CREATE_SUBGROUP,
    ADD_ROLE_TO_GROUP,
    REMOVE_ROLE_FROM_GROUP,

    // Identity provider
    GET_IDENTITY_PROVIDERS,
    GET_IDENTITY_PROVIDER,
    CREATE_IDENTITY_PROVIDER,
    UPDATE_IDENTITY_PROVIDER,
    DELETE_IDENTITY_PROVIDER,
    GET_IDENTITY_PROVIDER_MAPPERS,
    CREATE_IDENTITY_PROVIDER_MAPPER,

    // Authentication
    GET_AUTHENTICATION_FLOWS,
    GET_AUTHENTICATION_FLOW,
    CREATE_AUTHENTICATION_FLOW,
    DELETE_AUTHENTICATION_FLOW,
    GET_FLOW_EXECUTIONS,
    UPDATE_FLOW_EXECUTION,

    // User sessions & events (admin)
    GET_USER_SESSIONS,
    GET_USER_CONSENTS,
    REVOKE_USER_CONSENT,
    LOGOUT_USER,
    GET_OFFLINE_SESSIONS,
    GET_CLIENT_USER_SESSIONS,
    GET_CLIENT_OFFLINE_SESSIONS,
    CLEAR_USER_LOGIN_FAILURES,
    CLEAR_ALL_LOGIN_FAILURES,
    GET_USER_BRUTE_FORCE_STATUS,

    // Event streams (stores)
    GET_ADMIN_EVENTS,
    GET_USER_EVENTS,
    CLEAR_ADMIN_EVENTS,
    CLEAR_USER_EVENTS,

    // Components
    GET_COMPONENTS,
    GET_COMPONENT,
    CREATE_COMPONENT,
    UPDATE_COMPONENT,
    DELETE_COMPONENT,
    GET_SUB_COMPONENTS,

    // Keys
    GET_REALM_KEYS,

    // Required actions
    GET_REQUIRED_ACTIONS,
    GET_REQUIRED_ACTION,
    UPDATE_REQUIRED_ACTION,
    EXECUTE_ACTIONS_EMAIL,

    // Client scope ↔ role scope mappings
    GET_CLIENT_SCOPE_SCOPE_MAPPINGS,
    GET_CLIENT_SCOPE_MAPPED_REALM_ROLES,
    ADD_CLIENT_SCOPE_MAPPED_REALM_ROLES,
    REMOVE_CLIENT_SCOPE_MAPPED_REALM_ROLES,
    GET_CLIENT_SCOPE_MAPPED_CLIENT_ROLES,
    ADD_CLIENT_SCOPE_MAPPED_CLIENT_ROLES,
    REMOVE_CLIENT_SCOPE_MAPPED_CLIENT_ROLES,

    // User credentials
    GET_USER_CREDENTIALS,
    DELETE_USER_CREDENTIAL,
    MOVE_USER_CREDENTIAL,

    // User client-level roles
    GET_USER_CLIENT_ROLES,
    GET_USER_AVAILABLE_CLIENT_ROLES,
    ADD_CLIENT_ROLE_TO_USER,
    REMOVE_CLIENT_ROLE_FROM_USER,

    // Group client-level roles
    GET_GROUP_CLIENT_ROLES,
    GET_GROUP_AVAILABLE_CLIENT_ROLES,
    ADD_CLIENT_ROLE_TO_GROUP,
    REMOVE_CLIENT_ROLE_FROM_GROUP,

    // Authorization (confidential client UMA)
    GET_AUTHZ_RESOURCE_SERVER,
    UPDATE_AUTHZ_RESOURCE_SERVER,
    LIST_AUTHZ_RESOURCES,
    GET_AUTHZ_RESOURCE,
    CREATE_AUTHZ_RESOURCE,
    UPDATE_AUTHZ_RESOURCE,
    DELETE_AUTHZ_RESOURCE,
    LIST_AUTHZ_SCOPES,
    GET_AUTHZ_SCOPE,
    CREATE_AUTHZ_SCOPE,
    UPDATE_AUTHZ_SCOPE,
    DELETE_AUTHZ_SCOPE,
    LIST_AUTHZ_POLICIES,
    GET_AUTHZ_POLICY,
    CREATE_AUTHZ_POLICY,
    UPDATE_AUTHZ_POLICY,
    DELETE_AUTHZ_POLICY,
    GET_AUTHZ_RESOURCE_PERMISSION,
    CREATE_AUTHZ_RESOURCE_PERMISSION,
    UPDATE_AUTHZ_RESOURCE_PERMISSION,
    DELETE_AUTHZ_RESOURCE_PERMISSION,
    LIST_AUTHZ_SCOPE_PERMISSIONS,
    GET_AUTHZ_SCOPE_PERMISSION,
    CREATE_AUTHZ_SCOPE_PERMISSION,
    UPDATE_AUTHZ_SCOPE_PERMISSION,
    DELETE_AUTHZ_SCOPE_PERMISSION,

    // Realm: LDAP, user storage, sessions cache, client policies, registration
    TEST_LDAP_CONNECTION,
    SYNC_USER_STORAGE,
    PUSH_REALM_REVOCATION,
    LOGOUT_ALL_USERS,
    GET_REALM_CLIENT_POLICIES,
    UPDATE_REALM_CLIENT_POLICIES,
    GET_REALM_CLIENT_PROFILES,
    UPDATE_REALM_CLIENT_PROFILES,
    GET_CLIENT_REGISTRATION_PROVIDERS,

    // Localization
    GET_REALM_LOCALES,
    GET_LOCALIZATION_TEXTS,
    SAVE_LOCALIZATION_TEXT,
    DELETE_LOCALIZATION_TEXTS,
    DELETE_LOCALIZATION_TEXT,
    CREATE_OR_UPDATE_LOCALIZATION_TEXTS,

    // Organizations
    GET_ORGANIZATIONS,
    GET_ORGANIZATION,
    CREATE_ORGANIZATION,
    UPDATE_ORGANIZATION,
    DELETE_ORGANIZATION,
    GET_ORGANIZATION_MEMBERS,
    ADD_ORGANIZATION_MEMBER,
    REMOVE_ORGANIZATION_MEMBER,

    // User profile (declarative)
    GET_USER_PROFILE_CONFIG,
    UPDATE_USER_PROFILE_CONFIG,

    // Discourse
    SEARCH_DISCOURSE
}
